"""Added Customer Table.

Revision ID: ae5c3b7f430d
Revises: 53ba0a92746d
Create Date: 2021-12-11 19:01:25.859319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5c3b7f430d'
down_revision = '53ba0a92746d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('needle', sa.String(length=100), nullable=True),
    sa.Column('machine', sa.String(length=100), nullable=True),
    sa.Column('pigment', sa.String(length=100), nullable=True),
    sa.Column('brow_type', sa.String(length=100), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
